server:
  port: 6688
  db_url: "postgres://jeffery:postgres@localhost:5432/chat"
auth:
  sk: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIFLQTJ3ZSohPATdtOHyRd80vQGOh2bUpPH0j4IDx35Nz
    -----END PRIVATE KEY-----
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAncsAeQ2zHIaSqbhftpMm1OC2SncGuE9vPY1Khlo6pjc=
    -----END PUBLIC KEY-----
