### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "test",
    "fullname": "JefferyWang",
    "email": "111@qq.com",
    "password": "123456"
}

### signup alice

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "test",
    "fullname": "Alice",
    "email": "222@qq.com",
    "password": "123456"
}

### signin user(valid)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "111@qq.com",
    "password": "123456"
}

@token = {{signin.response.body.token}}

### signin user(invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "333@qq.com",
    "password": "123456"
}

### create chat
POST http://localhost:6688/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "project X",
    "members": [1, 2],
    "public": false
}

### create direct chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "members": [1, 2],
    "public": false
}


### get chat list

GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}


### get user list

GET http://localhost:6688/api/users
Authorization: Bearer {{token}}


### upload files

POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; filename="hello.txt"

Hello, World!
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; filename="cargo.png"
Content-Type: image/png

< ./fixtures/cargo.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### get files

GET http://localhost:6688/api/files/1/bc5/ff3/0faaf440731bcbc2653dcb49cf1ea6e8e1.png
Authorization: Bearer {{token}}


### send a message
POST http://localhost:6688/api/chats/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "Hello, World!",
    "files": []
}

### get messages
GET http://localhost:6688/api/chats/2/messages?last_id=8&limit=2
Authorization: Bearer {{token}}
